### ISSUE TITLE
autoconnect multiple ports bug

### ISSUE THREAD

**Issue by y1ds** [original-male/non#168] opened 2015-09-23 11:27 UTC
when multiple jack output ports are connected to a single mixer strip with one jack input port, only the first output port will be reconnected after restart. 
The amount of input ports has to be at least the number of inputs you want to connect in order for autoconnect to work. even if all output ports are connected to only on of the input ports.

**Comment by original-male** [comment] 2015-09-23 16:19
When you say "jack output ports", are you referring to strip outputs in non-mixer, or ports from another application? 

The autoconnect feature is not really meant for persisting connections across restarts, to accomplish effectively you need to use JACKPatch or some other program that can save/restore the entire JACK graph.

Were you using JACKPatch in this scenario?

**Comment by y1ds** [comment] 2015-09-24 13:47
With jack ouput ports I mean output ports from another application, I
use QjackCtl to save and restore my connection after restarts.

**Comment by original-male** [comment] 2015-09-24 18:20
Well, I think QjackCtl must not be saving/restoring your connections properly. I'm going to close this because it's not a bug. Consider using NSM and JACKPatch to manage your sessions.

**Closed by original-male** 2015-09-24 18:20 UTC

**Comment by y1ds** [comment] 2015-09-25 11:44
I think it is a bug, with other software I tried the same and this works
fine. In non mixer it is not possible to autoconnect multiple ports to a
single port. (at least with qjackctl, I will try these others as well)

**Comment by original-male** [comment] 2015-09-25 17:04
Could you give more information? When you say "autoconnect" are you referring to non-mixer's strip autoconnect feature or just to qjackctl's function as a connection manager? In JACK, the clients (non-mixer in this case) have nothing to do with the process of connection management whereby some other client (qjackctl) saves and restores those connections, so it's hard to see how what you're experiencing could possibly be a bug in non-mixer. If you were using JACKPatch then maybe it could be a bug in that, but you're not, so the only thing I can see being at fault here is QJackCtl.
